#!/bin/bash

readonly IMG="~/qemu_vms/2014-01-07-wheezy-raspbian.img"

qemu-system-arm -kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw" -hda ${IMG}
